# Site settings
title: NetCom Satelital
email: info@netcomsatelital.com.ar
description: Soluciones integrales de comunicaciones para su empresa.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://netcomsatelital.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "es"
  -
    scope:
      path: "es"
    values:
      lang: "es"
  -
    scope:
      path: "en"
    values:
      lang: "en"
